### PR TITLE
Update framework and support DeterministicDateTimeProvider

### PR DESCRIPTION
**Pull request by skarllot**
- Update projects to support .NET Standard 2.0;
- Update test projects to use .NET Core App 3.1;
- Update dependencies to the latest version;
- Support DeterministicDateTimeProvider for testing purposes.

### CODE REVIEW

**Comment by dennisroche** [comment]
thanks for this; will review. looks like the build is broken - not your fault.

**Comment by dennisroche** [comment]
were you using this library before making this change? interested in feedback as you'll know, this was created a long time ago. i use a different approach now to managing datetime in .NET.

**Comment by skarllot** [comment]
How is your approach now?

**Comment by dennisroche** [comment]
https://dennisroche.com/handle-date-and-or-time-with-precisiont/

Using NodaTime library and a static provider. 

The Rosyln Analyzer would be still useful to detect incorrect usages of `DateTime` and suggest the `NodaTime` static. You can also enforce that using Conventional tests https://github.com/andrewabest/Conventional.

With `Conventional`, add a rule:

    public class MustNotUseDateTimeNow : MustNotUsePropertyGetterSpecification<DateTime, DateTime>
    {
        internal MustNotUseDateTimeNow()
            : base(new Expression<Func<DateTime, DateTime>>[]
            {
                x => DateTime.Now,
                x => DateTime.UtcNow
            }, "Must not use DateTimeOffset.Now or DateTimeOffset.UtcNow. It is called {0} times in this type. Use NodaClock.Now or NodaClock.NowUtc")
        {
        }
    }

**Comment by dennisroche** [comment]
@skarllot still interested in getting this PR merged?

**Comment by skarllot** [comment]
Not so much, I giving a try with NodaTime.

**Pull request closed without merging**
